In [ ]:
#1
# y = 2x+5
def mylinear(x):

  y = 2*eval(x) + 5
  return y
userin = input("what number?")
print(mylinear(userin))

what number?56
117


In [ ]:
#2
a = input("x variable: ")
b = input("y variable: ")
c = input("z variable: ")
r1 = eval(a)
r2 = eval(b)
r3 = eval(c)
r = []
r.append(r1)
r.append(r2)
r.append(r3)
print(r)
d = input("x variable: ")
e = input("y variable: ")
f = input("z variable: ")
p1 = eval(d)
p2 = eval(e)
p3 = eval(f)
p = []
p.append(p1)
p.append(p2)
p.append(p3)
print(p)

def cross(r, p):

  y = [r2*p3 - r3*p2, r3*p1 - r1*p3, r1*p2 - r2*p1]

  return y

cross(r, p)



x variable3
y variable2
z variable4
[3, 2, 4]
x variable1
y variable3
z variable4
[1, 3, 4]
[-39  -3  34]


In [ ]:
#3
a =[]
lengthofvectora = input("How many components?")
components = eval(lengthofvectora)

while len(a) < components:
  variable = input("number: ")
  a.append(eval(variable))
print(a)

b = []
while len(b) < components:
  variable = input("number: ")
  b.append(eval(variable))
print(b)



def dotproduct(a, b):
  product = 0
  for x in range(components):
    product += a[x]*b[x]
  
  return product

print(dotproduct(a, b))






How many components?3
number1
number3
number4
[1, 3, 4]
number6
number2
number6
[6, 2, 6]
36


In [ ]:
#4
import numpy as np
mylist = [1, 2, 3]
myarray = np.array = ([1, 2, 3])

print(myarray*3)
print(mylist*3)



import numpy as np
A = np.array = ([[69, 420, 69, 420, 69, 420, 69],
[1, 0, 0, 42069, 0, 0, 0], [0, 1, 0, 666, 0, 0, 0], [0, 0, 1, np.pi, 0, 0, 0], [0, 0, 0, 1337, 1, 0, 0], [0, 0, 0, 42, 0, 1, 0], [0, 0, 0, 73, 0, 0, 1]])
A = np.delete(A, 0, axis=0)
print("deleting the first row gives:")
print(A)
A = np.delete(A, 3, axis=1)
print("deleting the fourth column gives:")
print(A)
x = np.array = ([[100], [35], [75], [4], [56], [38]])
A = np.append(A, x, axis=1)
print(A)


[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
deleting the first row gives:
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.20690000e+04
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 6.66000000e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.14159265e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.33700000e+03
  1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.20000000e+01
  0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.30000000e+01
  0.00000000e+00 0.00000000e+00 1.00000000e+00]]
deleting the fourth column gives:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[  1.   0.   0.   0.   0.   0. 100.]
 [  0.   1.   0.   0.   0.   0.  35.]
 [  0.   0.   1.

In [ ]:
def mylinear(x):

  y = 2*eval(x) + 5
  return y

testlist = [3, 0, 9, 2, 5]
testarray = np.array(testlist)
w = mylinear(testarray)
print(w)

testlist = [3, 0, 9, 2, 5]# these functions dont exist and cant perform on a list
c = mylinear(testlist)
print(c)

TypeError: ignored

In [ ]:
#5
#a
a= 5
b = 15
import numpy as np
d = np.dot(a, b)
print(d)

#b
arr1 = np.array = ([3, 4j])
arr2 = np.array = ([2, 2j])
x = np.dot(arr1, arr2)
print(x)

#c
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
c = np.dot(a, b)
print(c)

75
(-2+0j)
[[4 1]
 [2 2]]


In [ ]:
#6
from math import cosh , exp , e, pi 
x = 2*pi
a = cosh(x)
b = 0.5*(exp(x) + exp((-1)*(x)))
c = 0.5*(e**x + e**((-1)*(x))) 

if a == b:
  print("a = b")
if a != c:
  print("a != c")

print(a)
print(b)
print(c)

print(a == b != c)

tolerance = input("what is your tolerance:")
tol = eval(tolerance)
def difference(a, c):
  y = a - c

  if y <= tol :

    print(c)

  else:
    print("the difference btw a and c is greater than your tolerance")

print(difference(a, c))



a = b
a != c
267.7467614837482
267.7467614837482
267.74676148374806
True
what is your tolerance:0.000000000000000000001
 the difference btw a and c is greater than your tolerance
None


In [2]:
#7
mylist = []
lengthofvectora = input("How many components?")
components = eval(lengthofvectora)

while len(mylist) < components:# could use x = txt.split()
  variable = input("number")
  mylist.append(eval(variable))
print(mylist)

u = "reverse"
v = "normal"

def myfunc(list, T):
  if T == v:
    floatlist = [float(i) for i in mylist]
    return floatlist
  if T == u: 
    list.sort(reverse = True)
    floatlist = [float(i) for i in mylist]
    return floatlist

print(myfunc(mylist, v))


print(myfunc(mylist, u))


How many components?4
number1
number2
number3
number4
[1, 2, 3, 4]
[1.0, 2.0, 3.0, 4.0]
[4.0, 3.0, 2.0, 1.0]


In [ ]:
#8
testlist = [3, 0, 9, 2, 5] 
%timeit sorted(testlist) 
print(testlist)
%timeit testlist.sort() #this method is faster
print(testlist)





The slowest run took 10.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 313 ns per loop
[3, 0, 9, 2, 5]
The slowest run took 12.10 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 137 ns per loop
[0, 2, 3, 5, 9]


In [ ]:
import numpy

from numpy import mean
testlist = [3, 0, 9, 2, 5] 
mean(testlist)

import statistics
from statistics import mean

mean(testlist) #module.function()or variable.method()


3.8

In [ ]:
#9
import numpy as np
results = []
def Vol(*r):
  for x in r:
    v = (4/3)*np.pi*x**3
    results.append(v)
  return results

Vol(1, 3, 5, 2, 4)


[4.1887902047863905,
 113.09733552923254,
 523.5987755982989,
 33.510321638291124,
 268.082573106329]

In [ ]:
#10
# y= ax^2 + bx + c

def cubic(y = 0, TF = True):

  a = input("input a")
  b = input("input b")
  c = input("input c")
  D = (eval(b))**2 - 4*eval(a)*eval(c)
  if TF == True:

    if D < 0:
      rootD = (D)**(1/2)
      x3 = ((-1*eval(b)) + (rootD))/(2*(eval(a)))
      x4 = ((-1*eval(b)) - (rootD))/(2*(eval(a)))
      print(f"The complex solutions are {x3} and {x4}")

    elif D > 0:
      rootD = (D)**(1/2)
      print("There are two solutions")
      x1 = ((-1*eval(b)) + (rootD))/(2*(eval(a)))
      x2 = ((-1*eval(b)) - (rootD))/(2*(eval(a)))
      print(f"x1 = {x1} and x2 = {x2}")

    elif D == 0:
      print("There is one solutions")
      x = (-1*eval(b))/(2*(eval(a)))
      print(x)

cubic()

input a1
input b2
input c3
The complex solutions are (-0.9999999999999999+1.4142135623730951j) and (-1-1.4142135623730951j)


In [ ]:
#11
cubic(0, True)


input a2
input b-5
input c1
There are two solutions
x1 = 2.2807764064044154 and x2 = 0.21922359359558485


In [ ]:
#12
#Snipping
#snipet 1
n=2
def excitedState(n):
  n += 1  
  print(n) #print the local value

excitedState(n)
print(n)# prints global value

#snipet 2
N = 10000
def printGroundState(): 
  N=0
  print(N)#prints local value so 0

printGroundState() 
print(N)# prints global value = 10000

#snipet 3
spin = 0
def returnUpState():
  spin = 1 
  return spin # due to the return, the local value becomes the global value
spin = returnUpState() 
print(spin) #prints the new global value 


3
2
0
10000
1


In [ ]:
#13
#a
#Passing by value means that the value of the function parameter is copied
#into another location of your memory, and when accessing or modifying the variable within your function, 
#only the copy is accessed/modified and the original value is left untouched

#Passing by reference means that the value of the function parameter is copied
#into another location of your memory, and when accessing or modifying the variable within your function, 
#both the copy and the original value is accessed/modified 

#b
#modifying in-place is when you modify the local values of a function without changing the global value
index = 1
for i in range(1,10):
  index = i 
print(index)
#c
var = [5]
def timesTwo_inPlace(a): 
  a *= 2
timesTwo_inPlace(var) 
print(var)

#d
 # change this line with your answer to part(c)
def timesTwo(a):
  var = [5] 
  a = a*(2)
  
timesTwo(var)
print(var)

9
[5, 5]
[5, 5]


In [ ]:
#14
def kinematics(a, t): 
  x = (1/2) * a * t**2 #x is a local variable that is created and destroyed after the function is finished
  return x

accel = 0 # accel is a global fuction which never gets destroyed
time = 5
if accel >= 0:
  loc = kinematics(accel , time) # loc is a local variable describing the distance,
print(loc)                       #it gets destroyed after the if statement finishes
 #when accel = 0 it gave the smae value as when accel= 5 to fix this problem change > to >=


0.0


In [ ]:
#15
y = input("what number to factorialise:")
def factorial(x):
  fact = 1
  if x < 0:
    print("please input a positive number")
    
  elif x >= 0:
    for x in range(2, x+1):
      fact *= x
    return fact

  

factorial(eval(y))

what number to factorialise:4


24

In [ ]:
#16
userin3 = input("give a value for n: ")
userin4 = input("give a value for k: ")
def combine(n, k):
  if n >= k :
    result = (factorial(n))/((factorial(k))*(factorial(n-k)))
    return result

  if n < k:
    print(" n must be greater than k")
combine(eval(userin3), eval(userin4))
  

give a value for n: 14
give a value for k: 3


364.0

In [ ]:
#17
#(x+y)^n
m = input("value for x: ")
l = input("value for y: ")
o = input("value for n: ")
def binomial(x,y,n):
  if n >= 0:   #
    terms = x**n
    for k in range(1,n +1):
      terms += ((combine(n, k))*(x**(n-k))*(y**k))
      
    return terms

binomial(eval(m), eval(l), eval(o)) 

value for x: 3
value for y: 5
value for n: 3


512.0

In [ ]:
#18
def printHello(x): 
  if x == 1:
    print (" Hello world !") 
    else:
print("Bye world!")
# Here I assigned variable "b" to the function with x=0 b = printHello (0)
# Calling b is now equivalent to calling printHello(0) b

In [ ]:
def printHello(x): 
  if x == 1:
    print (" Hello world !") 
  else:
    print("Bye world!")
# Here I assigned variable "b" to the function with x=0 b = printHello (0)
# Calling b is now equivalent to calling printHello(0) b
printHello(1)

 Hello world !


In [8]:
#19
sum = 0
testlist = [3, 0, 9, 2, 5]
for i in testlist:
  
  sum += i
 

y = sum/ len(testlist)
print(y)
print(sum.__name__)

3.8


AttributeError: ignored