In [6]:


def mylinear(x):
  y = 2*x + 5
  return y

userin = input("what value for x: ")

print(mylinear(eval(userin)))
print(mylinear(3))


what value for x: 4
13
11


In [9]:
#find the cross product of 3D vector
a = input("x coord: ")
b = input("y coord: ")
c = input("z coord: ")

d = input("2nd x coord: ")
e = input("2nd y coord: ")
f = input("2nd z coord: ")

r = []
r1 = eval(a)
r2 = eval(b)
r3 = eval(c)
r.extend((r1, r2, r3))
print(r)

p = []
p1 = eval(d)
p2 = eval(e)
p3 = eval(f)
p.extend((p1, p2, p3))
print(p)

def cross(r, p):
  y = [r2*p3 - r3*p2, r3*p1 - r1*p3, r1*p2 - r2*p1]
  return y

cross(r, p)




x coord: 1
y coord: 2
z coord: 3
2nd x coord: 4
2nd y coord: 5
2nd z coord: 6
[1, 2, 3]
[4, 5, 6]


[-3, 6, -3]

In [10]:
#find dot product of a vector at length of users choice

a = []
lengthofvectora = input("how many components: ")
components = eval(lengthofvectora)

while len(a) < components :
  variable = input("coordinate: ")
  coord = eval(variable)
  a.append(coord)

print(a)

b = []
while len(b) < components :
  variableb = input("coordinate: ")
  coordb = eval(variableb)
  b.append(coordb)

print(b)

def dotproduct(a, b):
  product = 0
  for x in range(components):
    product = product + a[x]*b[x]

  return product

dotproduct(a, b)


how many components: 5
coordinate: 1
coordinate: 2
coordinate: 3
coordinate: 4
coordinate: 5
[1, 2, 3, 4, 5]
coordinate: 3
coordinate: 4
coordinate: 5
coordinate: 6
coordinate: 7
[3, 4, 5, 6, 7]


85

In [22]:
import numpy as np
array = np.array([1, 2, 3])
mylist = [1, 2, 3]

print(mylist*3)#repeats list three times into one list

print(array*3) #multiplies each element in array by 3 and prints it

def mylinear(x):
  y = 2*x + 5
  return y

testlist = [3, 0, 9, 2, 5]

testarray = np.array(testlist)
print(testarray)
print(mylinear(testarray))

print(mylinear(testlist)) #cant perform a funtion on a list but can do it on an array
print(mylinear(int(testlist)))

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
[3 0 9 2 5]
[11  5 23  9 15]


TypeError: ignored

In [49]:

import numpy as np
A = np.array([[69, 420, 69, 420, 69, 420, 69],
              [1, 0, 0, 42069, 0, 0, 0], 
              [0, 1, 0, 666, 0, 0, 0], 
              [0, 0, 1, np.pi, 0, 0, 0], 
              [0, 0, 0, 1337, 1, 0, 0], 
              [0, 0, 0, 42, 0, 1, 0], 
              [0, 0, 0, 73, 0, 0, 1]])

A = np.delete(A, 0, 0)# deletes the first row from A
A = np.delete(A, 3, 1)# deletes the 4th column from A

print(A)

Newarray = np.array([21, 13, 420, 69, np.pi, 5]) #new array to be added to colum 
A = np.insert(A, 3, Newarray, axis=1)#3 is the column that the Newarray will be added to 

print(A)

Narray = np.array([1, 2, 3, 4, 5, 6, 7])
A = np.insert(A, 1, Narray, axis=0)# add new row of Narray to A on the second row thus there is a 1
print(A)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[  1.           0.           0.          21.           0.
    0.           0.        ]
 [  0.           1.           0.          13.           0.
    0.           0.        ]
 [  0.           0.           1.         420.           0.
    0.           0.        ]
 [  0.           0.           0.          69.           1.
    0.           0.        ]
 [  0.           0.           0.           3.14159265   0.
    1.           0.        ]
 [  0.           0.           0.           5.           0.
    0.           1.        ]]
[[  1.           0.           0.          21.           0.
    0.           0.        ]
 [  1.           2.           3.           4.           5.
    6.           7.        ]
 [  0.           1.           0.          13.           0.
    0.           0.        ]
 [  0.           0.           1.         420.           0.
    0.           0.  

In [56]:
import numpy as np

print(np.dot(2,4))

arr1 = np.array([3, 4j])
arr2 = np.array([2, 2j])

print(np.dot(arr1, arr2))

a = np.array([[1, 0],
             [0, 1]])
b = np.array([[4, 1],
             [2, 2]])
print(np.dot(a, b))

8
(-2+0j)
[[4 1]
 [2 2]]


In [64]:
from math import cosh, exp, e, pi

x = 2 *pi
a = cosh(x)
b = 0.5 *(exp(x) + exp(x*-1))
c = 0.5 *(e**x + e**(x*-1)) 
if a == b:
  print("a = b")
if a != c:
  print("a != c")

print(a)
print(b)
print(c)

print(a == b != c)

tolerance = eval(input("tolerance: "))

def difference(a, c):
  y = a - c

  if y <= tolerance:
    print(f" c = {c}")
  
  elif y > tolerance:
    print(f"the difference between a and c is greater than your tolerance")

print(difference(a, c))

a = b
a != c
267.7467614837482
267.7467614837482
267.74676148374806
True
tolerance: 0
the difference between a and c is greater than your tolerance
None


In [90]:
userin = input("how many components: ")#to find number of compenents then turned into integer with eval
components = eval(userin)
mylist = []

while len(mylist) < components:
  variable = eval(input("number: "))#creates a list from the user
  mylist.append(variable)

print(mylist)

u = "reverse"
v = "normal"

def myfunc(list, T):#function that sorts the list and then either reverses it or keeps it sorted 
  if T == u:
    mylist.sort(reverse = True)
    floatlist = [float(i) for i in mylist]
    return floatlist


  if T == v:
    mylist.sort()
    floatlist = [float(x) for x in mylist]
    return floatlist 
  
  
print(myfunc(mylist, v))
print(myfunc(mylist, u))




how many components: 5
number: 2
number: 9
number: 8
number: 1
number: 5
[2, 9, 8, 1, 5]
[1.0, 2.0, 5.0, 8.0, 9.0]
[9.0, 8.0, 5.0, 2.0, 1.0]


In [109]:
testlist = [3, 0, 9, 2, 5] 
%timeit sorted(testlist)#%timeit times how long the process takes
%timeit testlist.sort()

import statistics as st
from statistics import mean 
print(mean(testlist))
%timeit mean(testlist)
print(np.mean(testlist))
%timeit np.mean(testlist)


The slowest run took 13.24 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 303 ns per loop
The slowest run took 50.09 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 145 ns per loop
3.8
100000 loops, best of 3: 13.5 µs per loop
3.8
The slowest run took 9.93 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.61 µs per loop


In [105]:
testlist = [3, 0, 9, 2, 5] 
import numpy as np
from numpy import mean
print(np.mean(testlist))
%timeit np.mean(testlist)

3.8
The slowest run took 6.35 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.62 µs per loop


In [110]:
testlist = [3, 0, 9, 2, 5] 
M = sum(testlist)/len(testlist)
print(M)
%timeit M


3.8
10000000 loops, best of 3: 20.5 ns per loop


In [115]:
import numpy as np 

results = []#use empty list to add volume results to 

def Volume(*r):#use *r inside function to denote a list of r's can be used
  for x in r:
    V = 4/3 * np.pi * x**3
    results.append(V)
  return results

Volume(5, 3, 1, 2, 7)

[523.5987755982989,
 113.09733552923254,
 4.1887902047863905,
 33.510321638291124,
 1436.7550402417319]

In [2]:
# y= ax^2 + bx + c
def cubic(y = 0, TF = True):
  a = input("input a")
  b = input("input b")
  c = input("input c")

  print(a)
  print(b)
  print(c)

  D = (eval(b))**2 - 4*eval(a)*eval(c)
  if TF == True :
    if D < 0:
      rootD = (D)**(1/2)
      print("There are two complex solutions")
      x1 = ((-1*eval(b)) + (rootD))/(2*(eval(a)))
      x2 = ((-1*eval(b)) - (rootD))/(2*(eval(a)))
      print(f"x1 = {x1} and x2 = {x2}")

    if D > 0:
      rootD = (D)**(1/2)
      print("There are two solutions")
      x3 = ((-1*eval(b)) + (rootD))/(2*(eval(a)))
      x4 = ((-1*eval(b)) - (rootD))/(2*(eval(a)))
      print(f"x1 = {x3} and x2 = {x4}")

    if D == 0:
      print("There is one solutions")
      x = (-1*eval(b))/(2*(eval(a)))
      print(x)

cubic()


input a2
input b-5
input c1
2
-5
1
There are two solutions
x1 = 2.2807764064044154 and x2 = 0.21922359359558485


In [3]:
cubic(0, True)


input a2
input b-5
input c1
2
-5
1
There are two solutions
x1 = 2.2807764064044154 and x2 = 0.21922359359558485


In [8]:
#Local variables in a function are created when the function is called, 
#and destroyed when the function has finished execution. 
#Global variables are created at the start of the program and exists until the program finishes execution.

n=2 #global variable 
def excitedState(n):
  n += 1 
  print(n)#local variable n is printed and is different to the global variable n due to the function
excitedState(n) 
print(n)  #global variable is printed

N=5#this global variable was added such that the code below could run
def printGroundState(): 
  N=0
  print(N)#prints the local variable due to the function where N=0
printGroundState() 
print(N)# since there is no global variable an error occurs as it cant print it 

spin = 0#initial global variable
def returnUpState():
  spin = 1 #local variable due to function
  return spin
spin = returnUpState()# now the global variable is converted to the local variable 
print(spin)# thus when the printing of the global variable is wanted it prints the local


3
2
0
5
1


In [15]:
var = [5] # this first line was var = 5 now changed to var =[5] such that the outcome is [5,5]
def timesTwo_inPlace(a): 
  a *= 2
timesTwo_inPlace(var) 
print(var)


def timesTwo_inPlace(a): 
  var = [5] 
  a = a * 2
timesTwo_inPlace(var) 
print(var)

index = 1
for i in range(1,10): #for loops and if/else do not have their own local and global variables
  index = i 
print(index)

[5, 5]
[5, 5]
9


In [19]:

def kinematics(a, t): 
  x = 1/2 * a * t**2 #x is a local and gets destoyed once the function finishes
  return x
accel = 0 #accel is a global and never gets destoyed
time = 5
if accel >= 0:
  loc = kinematics(accel , time)# loc is a local and is destoyed once the if statement finishes
print(loc)
#when accel = 5 it gives the same answer when accel = 0
#change this by turning > to >=

0.0


In [25]:
userin = input("what value to factorial: ")
def factorial(x):
  fact = 1
  if x < 0:
    print(f"please input a positive number")

  elif x >= 0:
    for x in range(2, x+1):
      fact = fact * x
    return fact

factorial(eval(userin))

what value to factorial: 2


2

In [32]:
Nuserin = input("what value for n: ")
Kuserin = input("what value for k: ")


def combine(n, k):
  if n < k:
    print(f"let n be greater than k")

  elif n >= k:
    result = factorial(n)/(factorial(k)*factorial(n - k))#using same function from above
  return result

combine(eval(Nuserin), eval(Kuserin))

what value for n: 10
what value for k: 4


210.0

In [35]:
#(x + y )^n
Xuserin = input("what value for x: ")
Yuserin = input("what value for y: ")
nuserin = input("what value for n: ")

def binomial(x, y, n):
  if n < 0:
    print("please input a positive n")# cant use binomial expansion on a negative n 

  elif n >= 0:
    terms = x**n# this is the first term of the binomial expansion
    for k in range(1, n + 1):
      terms = terms + (combine(n, k)*x**(n - k)*y**(k))
    return terms

binomial(eval(Xuserin), eval(Yuserin), eval(nuserin))

what value for x: 10
what value for y: 12
what value for n: 3


10648.0

In [38]:
lambdaHypothenuse = lambda x, y: (x*x + y*y)**(1/2) #lambda function - its a one liner function
lambdaHypothenuse(3,4)

5.0

In [87]:
inputs = [-7, -1, -12, 0, 2, 5, 7, 8]
L = list(map(lambda x: 2*x + 5, inputs))#Map is a Python built-in function that takes in a function and 
                                        #a sequence as arguments and then calls the input function on each item of the sequence

print(L)
L2 = list(filter(lambda x: (x >= 0), L))#filter is a built- in function that needs two arguements (1)x>= 0 and 
                                        #(2) a list to extract the elements that are true for the first arguement
print(L2)
results = []
def positive(r):#use singular letter instead of *r as then you can use an array or list as arguement for the function
  for x in r:#for loop used so each number in array is used in the function
    y = 2*x + 5
    if y >= 0:# if statement filters out negative outputs 
      results.append(y)#positive outputs are added to an empty list
  return results

arr = np.array(inputs)    
print(arr)
print(positive(inputs))



[-9, 3, -19, 5, 9, 15, 19, 21]
[3, 5, 9, 15, 19, 21]
[ -7  -1 -12   0   2   5   7   8]
[3, 5, 9, 15, 19, 21]
