In [3]:
#Excersise 1 
#finding the determinant 

import numpy as np

#defining a function that calculates the determinant of a matrix
def determinant(A):
  if len(A) == 1: #if matrix is an 1x1 then the determinant is just the matrix entry
    detA = A[0][0]

    return detA

  if len(A) == 2: #if matrix is 2x2 then the determinant is ad-cb
    detA = A[0][0]*A[1][1] - A[1][0]*A[0][1]

    return detA

  if len(A) > 2: #if matrix is greater than a 2x2 matrix then calculate using the determinant formula 
    detA = 0
    for x in range(0, len(A)):
      delA = np.delete(A,0,0) # this will be used for the first deleting of rows and columns
      delA = np.delete(delA,x,1)# this will be used if the formula requires to go through the loop more than twice 
      detA += (-1)**x*A[0][x]*determinant(delA) #imbedded function to restart the loop for new matrix
      

  return detA

arr = np.array = ([[5,5.3,0,4], # this is a random 5x5 matrix that I created to check the determinant
                   [2,4.89,3,1.2], 
                   [-2,3,1,24], 
                   [3,3,0,3.54]])

determinant(arr)

-141.2430000000001

In [ ]:
import numpy as np

A = np.array = ([[1,2,3,4], # this is a random 4x4 matrix that I created to check the determinant
                   [5,6,7,8], 
                   [9,10,11,12], 
                   [13,14,15,16]])
detA = 0
for x in range(0, len(A)):
  delA = np.delete(A,0,0) # this will be used for the first deleting of rows and columns
  delA = np.delete(delA,x,1)# this will be used if the formula requires to go through the loop more than twice 

  detA += (-1)**x*A[0][x]*determinant(delA) #imbedded function to restart the loop for new matrix
  print(delA)

print(detA)



[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 5  7  8]
 [ 9 11 12]
 [13 15 16]]
[[ 5  6  8]
 [ 9 10 12]
 [13 14 16]]
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
0


In [4]:
#Excersise 2 
# Taylor expansion on sinx compared to np.sinx

# function that calculates the taylor expansion of sin(x)
import numpy as np

def factorial(x): #the factorial function turns aan input n into n!
  fact = 1 #start with fact = 1 as 0! = 1
  if x < 0:  # because you can only find the factorial of positive numbers 
    print("please input a positive number")
    
  elif x >= 0:
    for x in range(2, x+1): #use a for loop so fact increses in size as x increases from 2 to x ( use x+1 as range starts from 0 to x-1 so add the 1 to make it x)
      fact *= x
    return fact

print(factorial(6))  
  


def taylorexpansion(x, n): # taylor expansion of sin(x) function x = radians and n = number of iterations
  
  taylor = 0                #taylor = sin(x) equal to 0 as the for loop adds to this number
  for i in range(0,n+1):    # using a for loop of i from 0 to n= number of iterations then we can manipulate number of i
    taylor += (((-1)**i)*(x**((2*i)+1)))/(factorial((2*i)+1)) # (-1)**1 gives +ve and then -ve number switching each iteration
  return taylor                                               #manipulate the i to become 2*i + 1 so its alwys odd # then divide by the factorial function
                  #use the += so it keeps adding to the previous number                               #manipulte i again so number factorised is always odd

taylorexpansion(np.pi, 50)

z = taylorexpansion(np.pi/2, 2)
v = np.sin(np.pi/2)
%timeit np.sin(np.pi/2)    #timing the numpy version and the function I defined and comparing
%timeit taylorexpansion(np.pi/2, 80)

print(f"taylorexpansion function obtained: {z: 5f} and numpy sin obtained: {v: 5f}")#using an f string to print the expression to 5 significant figures 

if abs((z - v)) <= 10**-5 :#Using a boolean to print if else statemments and the abs() is used to obtain the absolute value of the difference between the numpy sin and the functions sin
  print(f'they are within a range of 10**-5') 

else :
  print(f'they are not within the range of 10**-5')
                

720
The slowest run took 14.46 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 912 ns per loop
1000 loops, best of 3: 502 µs per loop
taylorexpansion function obtained:  1.004525 and numpy sin obtained:  1.000000
they are not within the range of 10**-5


In [21]:
#Excersise 3
#Please note that the skeleton provided to me does not work for some reason on this python document but if moved to a new one the whole code works smoothly
import numpy as np
import numpy.random as rd
#

def generate_data(N: int) -> tuple:
  """
  Generates N random massive objects with their masses, positions
  and momenta.

  :param int N: The amount of massive objects to generate.

  :returns: A tuple of three numpy.ndarrays; one of shape (N,) containing
  masses (in kg), one of shape (3, N) containing momenta (in kg m/s)
  and one of shape (3, N) containing positions (in m).
  (The ith column of momenta and positions give the coordinates belonging
  to the object at index i in masses.)
  """
  masses = rd.randint(20, 200, size = N) #used in this function to obtain a random tuple of integers of size N with values from 20 to 200
  momenta = rd.randint(50, 500, size=(3, N))#used in this function to obtain a random tuple array of integers of size N colums and 3 rows with values from 50 to 500
  positions = rd.randint(20, 200, size=(3, N))

  
  return masses, momenta, positions

Data = generate_data(2) #generating data so there are two values/arrays per masses, positions, and momenta
print(Data)
mass, momenta, position = Data
print(mass)
print(momenta)

m1, m2 = tuple(mass)
print(f" m1 = {m1} m2 = {m2}")

r1 = tuple(position[0:3, 0])#makes a tuple of the fist column of the positions array 
print(f"r1 = {r1}")
r2 = tuple(position[0:3, 1])#makes a tuple of the second column of the position array
print(f"r2 = {r2}")
p1 = tuple(momenta[0:3, 0])#makes a tuple of the first column of the momenta array
print(f"p1 = {p1}")
p2 = tuple(momenta[0:3, 1])#makes a tuple of the second column of the momenta array
print(f"p2 = {p2}")

pos = tuple(position.transpose())#transposing the position tuple so the r1 and r2 tupple are now row vectors instead of column vectors
print(pos[0], type(pos))

mom = tuple(momenta.transpose())#transposing the position tuple so the p1 and p2 tupple are now row vectors instead of column vectors
print(mom[0][0], type(mom))

def find_potential_energy(m, r):

  G=6.67*10**-11
  A= -1*G*m[0]*m[1]#defining the neumorator
  B = abs(r[0]-r[1])#defining the denominator as the absolute value of the difference between the vectors 
  C = np.linalg.norm(B)#normalising the difference between the vectors 
  V = A/C #formula for the potential energy 
  return V

V = find_potential_energy(mass, pos)# using the masses and the transposed position tuples 
print(f"the potential energy is :V = {V} J", type(V))#using an f string to print the value of V and to check the type of V is a float

def find_kinetic_energy(m, p):
  p1 = round(np.linalg.norm(p[0]), 5)# using the round function to return the float inside(normalising vector p1) to 5 decimal places 
  p2 = round(np.linalg.norm(p[1]), 5)# using the round function to return the float inside(normalising vector p2) to 5 decimal places 
  T = round((p1**2/(2*m[0]) + p2**2/(2*m[1])), 5)# formula to find the values of the kinetic energy 
  return T

T = find_kinetic_energy(mass, mom)#using the masses and the transposed momentum tuples 
print(f"the kinetice energy is:T = {T} J", type(T))#using an f string to print the value of the kinetic energy and to check the type of T = is a float

def find_angular_momentum(p, r):
  A = np.cross(r[0], p[0], axis = 0)# use the np.cross to find the cross product of a three row vectors r1 and p1
  B = np.cross(r[1], p[1], axis = 0)# use the np.cross to find the cross product of a three row vectors r2 and p2
  L = A + B #add the previous cross products together to obtain the angular momentum 
  return L 

L = find_angular_momentum(mom, pos)#using the transposed momentum and position tuples
print(f"the angular momentum is: {L} kgm^2/s^2", type(L))

E = T + V #final energgy is the sum of the potential energy and the kinetic energy 
print(f"the total energy and angular momentum are:E = {E} J and L = {L} kgm^2/s^2")#printed with an f string are the total energy and the angular momentum

TypeError: ignored