In [ ]:
#Home Work 2
#Byron Rusch
#s3906442

#1
def Fizzbuzz(stop): # function tells the program to stop at a certain number of iterations
   
  fizzbuzz = [] #empty list so all elements can be appended
  x = 1
  while x < stop +1 :
    if x % 3 == 0 and x % 5 != 0 : #add fizz to the list if x is div by 3
      fizzbuzz.append("Fizz")

    elif x % 5 == 0 and x % 3 != 0 : #add buzz to the list if x is div by 5
      fizzbuzz.append("Buzz")

    elif x % 3 == 0 and x % 5 == 0: #add fizzbuzz to the list if x is div by 3 and 5
      fizzbuzz.append("FizzBuzz")
  
    else:                         #add x to the list if x in undivisable by 3 or 5
      fizzbuzz.append(x)

    x += 1
  return fizzbuzz


Fizzbuzz(16) #tells the programm to stop at 16 loop 



[1,
 2,
 'Fizz',
 4,
 'Buzz',
 'Fizz',
 7,
 8,
 'Fizz',
 'Buzz',
 11,
 'Fizz',
 13,
 14,
 'FizzBuzz',
 16]

In [ ]:
#2
import numpy as np

#defining a function that calculates the determinant of a matrix
def determinant(A):
  if len(A) == 1: #if matrix is an 1x1 then the determinant is just the matrix entry
    detA = A[0][0]

    return detA

  if len(A) == 2: #if matrix is 2x2 then the determinant is ad-cb
    detA = A[0][0]*A[1][1] - A[1][0]*A[0][1]

    return detA

  if len(A) > 2: #if matrix is greater than a 2x2 matrix then calculate using the determinant formula 
    detA = 0
    for x in range(0, len(A)):
      delA = np.delete(A,0,0) # this will be used for the first deleting of rows and columns
      delA = np.delete(delA,x,1)# this will be used if the formula requires to go through the loop more than twice 
      detA += (-1)**x*A[0][x]*determinant(delA) #imbedded function to restart the loop for new matrix
      x += 1

  return detA

arr = np.array = ([[0.53,5.3,0,4], # this is a random 5x5 matrix that I created to check the determinant
                   [2,4.89,3,1.2], 
                   [-2,2 + 3j,1,24], 
                   [3 - 2j,3,0,3.54]])

determinant(arr)

(-984.0065820000002+832.7141999999999j)

In [ ]:
#3a
# function that calculates the taylor expansion of sin(x)
import numpy as np

def factorial(x): #the factorial function turns aan input n into n!
  fact = 1
  if x < 0:
    print("please input a positive number")
    
  elif x >= 0:
    for x in range(2, x+1): #use a for loop so fact increses in size as x increases from 2 to x
      fact *= x
    return fact


def taylorexpansion(x, n): # taylor expansion of sin(x) function x = radians and n = number of iterations
  
  taylor = 0                #taylor = sin(x) equal to 0 as the for loop adds to this number
  for i in range(0,n+1):    # using a for loop of i from 0 to n= number of iterations then we can manipulate number of i
    taylor += (((-1)**i)*(x**((2*i)+1)))/(factorial((2*i)+1)) # (-1)**1 gives +ve and then -ve number switching each iteration
  return taylor                                               #manipulate the i to become 2*i + 1 so its alwys odd # then divide by the factorial function
                             #use the += so it keeps adding to the previous number                               #manipulte i again so number factorised is always odd
taylorexpansion(np.pi, 84)
                

3.3280566969799443e-16

In [ ]:
#3b
import numpy as np
print(np.sin(np.pi/2))



def factorial(x):
  fact = 1
  if x < 0:
    print("please input a positive number")
    
  elif x >= 0:
    for x in range(2, x+1): #use a for loop so fact increses in size as x increases from 2 to x
      fact *= x
    return fact


def taylorexpansion(x, n): # taylor expansion of sin(x) function x = radians and n = number of iterations
  
  taylor = 0                #taylor = sin(x) equal to 0 as the for loop adds to this number
  for i in range(0,n+1):    # using a for loop of i from 0 to n= number of iterations then we can manipulate number of i
    taylor += (((-1)**i)*(x**((2*i)+1)))/(factorial((2*i)+1)) # (-1)**1 gives +ve and then -ve number switching each iteration
  return taylor                                               #manipulate the i to become 2*i + 1 so its alwys odd # then divide by the factorial function
                             #use the += so it keeps adding to the previous number                               #manipulte i again so number factorised is always odd
print(taylorexpansion(np.pi/2, 84))

z = taylorexpansion(np.pi/2, 84)
v = np.sin(np.pi/2)
%timeit np.sin(np.pi/2)
%timeit taylorexpansion(np.pi/2, 80)

print(f"taylorexpansion function obtained: {z: 5f} and numpy sin obtained: {v: 5f}")

if abs((z - v)) <= 10**-5 :
  print(f'they are within a range of 10**-5')

else :
  print(f'they are not within the range of 10**-5')


1.0
1.0000000000000002
The slowest run took 18.48 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 986 ns per loop
1000 loops, best of 3: 497 µs per loop
taylorexpansion function obtained:  1.000000 and numpy sin obtained:  1.000000
they are within a range of $10**-5$


In [2]:
import numpy as np
import numpy.random as rd

def generate_data(N: int) -> tuple:
  """
  Generates N random massive objects with their masses, positions
  and momenta.

  :param int N: The amount of massive objects to generate.

  :returns: A tuple of three numpy.ndarrays; one of shape (N,) containing
  masses (in kg), one of shape (3, N) containing momenta (in kg m/s)
  and one of shape (3, N) containing positions (in m).
  (The ith column of momenta and positions give the coordinates belonging
  to the object at index i in masses.)
  """
  masses = rd.randint(10, 200, size=N)
  momenta = rd.randint(50, 500, size=(3, N))
  positions = rd.randint(20, 200, size=(3, N))

  return masses, momenta, positions

Data = generate_data(2)
print(Data)
mass, momenta, position = Data
print(mass)
print(momenta)

m1, m2 = tuple(mass)
print(f" m1 = {m1} m2 = {m2}")

r1 = tuple(position[0:3, 0])
print(f"r1 = {r1}")
r2 = tuple(position[0:3, 1])
print(f"r2 = {r2}")
p1 = tuple(momenta[0:3, 0])
print(f"p1 = {p1}")
p2 = tuple(momenta[0:3, 1])
print(f"p2 = {p2}")

pos = tuple(position.transpose())
print(pos[0], type(pos))

mom = tuple(momenta.transpose())
print(mom[0][0], type(mom))

def find_potential_energy(m, r):

  G=6.67*10**-11
  A= -1*G*m[0]*m[1]
  B = abs(r[0]-r[1])
  C = np.linalg.norm(B)
  V = A/C 
  return V

V = find_potential_energy(mass, pos)
print(f"the potential energy is :V = {V} J", type(V))

def find_kinetic_energy(m, p):
  p1 = round(np.linalg.norm(p[0]), 5)
  p2 = round(np.linalg.norm(p[1]), 5)
  T = round(p1**2/(2*m[0]) + p2**2/(2*m[1]), 5)
  return T

T = find_kinetic_energy(mass, mom)
print(f"the kinetice energy is:T = {T} J", type(T))

def find_angular_momentum(p, r):
  A = np.cross(r[0], p[0], axis = 0)
  B = np.cross(r[1], p[1], axis = 0)
  L = A + B 
  return L 

L = find_angular_momentum(mom, pos)
print(f"the angular momentum is: {L} kgm^2/s^2", type(L))

E = T + V
print(f"the total energy and angular momentum are:E = {E} J anf L = {L} kgm^2/s^2")


(array([89, 75]), array([[486, 494],
       [496,  95],
       [300, 249]]), array([[174, 169],
       [ 56,  61],
       [ 49, 179]]))
[89 75]
[[486 494]
 [496  95]
 [300 249]]
 m1 = 89 m2 = 75
r1 = (174, 56, 49)
r2 = (169, 61, 179)
p1 = (486, 496, 300)
p2 = (494, 95, 249)
[174  56  49] <class 'tuple'>
486 <class 'tuple'>
the potential energy is :V = -3.41973342046356e-09J <class 'numpy.float64'>
the kinetice energy is:T = 5315.08751J <class 'numpy.float64'>
the angular momentum is: [-9320 17959 45009]kgm^2/s^2 <class 'numpy.ndarray'>
the total energy and angular momentum are:E = 5315.087509996581J anf L = [-9320 17959 45009]


In [ ]:
import numpy as np
import numpy.random as rd

def generate_data(N: int) -> tuple:
  """
  Generates N random massive objects with their masses, positions
  and momenta.

  :param int N: The amount of massive objects to generate.

  :returns: A tuple of three numpy.ndarrays; one of shape (N,) containing
  masses (in kg), one of shape (3, N) containing momenta (in kg m/s)
  and one of shape (3, N) containing positions (in m).
  (The ith column of momenta and positions give the coordinates belonging
  to the object at index i in masses.)
  """
  masses = rd.randint(10, 200, size=N)
  momenta = rd.randint(50, 500, size=(3, N))
  positions = rd.randint(20, 200, size=(3, N))

  return masses, momenta, positions

masses, momenta, positions = generate_data(N)


def find_kinetic_energy(m, p, N):
  T_momenta = np.transpose(m)
  momentum = [round(np.linalg.norm(p[i]), 5)**2 for i in range(N)]
  E_K = [momentum[i]/(2*m[i]) for i in range (N)]
  p2 = round(np.linalg.norm(p[1]), 5)
  T = p1**2/(2*m[0]) + p2**2/(2*m[1])
  return T

T = find_kinetic_energy(mass, mom)
print(f"the kinetice energy is:T = {T}J", type(T))

def find_angular_momentum(p, r):
  A = np.cross(r[0], p[0], axis = 0)
  B = np.cross(r[1], p[1], axis = 0)
  L = A + B 
  return L 

L = find_angular_momentum(mom, pos)
print(f"the angular momentum is: {L}kgm^2/s^2", type(L))

def find_potential_energy(m, r):

  G=6.67*10**-11
  A= -1*G*m[0]*m[1]
  B = abs(r[0]-r[1])
  C = np.linalg.norm(B)
  V = A/C 
  return V

V = find_potential_energy(mass, pos)
print(f"the potential energy is :V = {V}J", type(V))

def collect_data(N):
  rawdata = generate_data(N)
  print(rawdata)
  mass, momenta, position = Data
  pos = tuple(position.transpose())
  mom = tuple(momenta.transpose())
  KE = find_kinetic_energy(mass, mom)
  PE = find_potential_energy(mass, pos)
  L = find_angular_momentum(mom, pos)
  return f"the kinetic energy is {KE}J, the potential energy is {PE}J and the angular momentum is {L}kgm^2/s^2"

print(collect_data(10))
6,16
3,9


the kinetice energy is:T = 6670.8203651031035J <class 'numpy.float64'>
the angular momentum is: [37796  3979  5300]kgm^2/s^2 <class 'numpy.ndarray'>
the potential energy is :V = -1.7234811827367612e-09J <class 'numpy.float64'>
(array([172, 152, 102,  39,  78,  96,  80,  39,  38, 128]), array([[459, 139,  87,  53, 336, 304, 168, 308, 452,  87],
       [211, 136, 131, 249, 421, 340, 265, 220, 190, 324],
       [448,  96,  97, 458, 189, 420, 191, 421, 390, 130]]), array([[ 29, 164, 169,  96, 185, 100, 167,  38,  50,  34],
       [ 73,  58, 195,  22,  83,  81, 172, 179,  99,  81],
       [ 27, 161,  83, 115,  51, 181,  57,  86, 195, 191]]))
the kinetic energy is 6670.8203651031035J, the potential energy is -1.7234811827367612e-09J and the angular momentum is [37796  3979  5300]kgm^2/s^2


In [3]:
#Excersise 3
#Please note that the skeleton provided to me does not work for some reason on this python document but if moved to a new one the whole code works smoothly
import numpy as np
import numpy.random as rd
#

def generate_data(N: int) -> tuple:
  """
  Generates N random massive objects with their masses, positions
  and momenta.

  :param int N: The amount of massive objects to generate.

  :returns: A tuple of three numpy.ndarrays; one of shape (N,) containing
  masses (in kg), one of shape (3, N) containing momenta (in kg m/s)
  and one of shape (3, N) containing positions (in m).
  (The ith column of momenta and positions give the coordinates belonging
  to the object at index i in masses.)
  """
  masses = rd.randint(20, 200, size = N) #used in this function to obtain a random tuple of integers of size N with values from 20 to 200
  momenta = rd.randint(50, 500, size=(3, N))#used in this function to obtain a random tuple array of integers of size N colums and 3 rows with values from 50 to 500
  positions = rd.randint(20, 200, size=(3, N))

  
  return masses, momenta, positions

Data = generate_data(2) #generating data so there are two values/arrays per masses, positions, and momenta
print(Data)
mass, momenta, position = Data
print(mass)
print(momenta)

m1, m2 = tuple(mass)
print(f" m1 = {m1} m2 = {m2}")

r1 = tuple(position[0:3, 0])#makes a tuple of the fist column of the positions array 
print(f"r1 = {r1}")
r2 = tuple(position[0:3, 1])#makes a tuple of the second column of the position array
print(f"r2 = {r2}")
p1 = tuple(momenta[0:3, 0])#makes a tuple of the first column of the momenta array
print(f"p1 = {p1}")
p2 = tuple(momenta[0:3, 1])#makes a tuple of the second column of the momenta array
print(f"p2 = {p2}")

pos = tuple(position.transpose())#transposing the position tuple so the r1 and r2 tupple are now row vectors instead of column vectors
print(pos[0], type(pos))

mom = tuple(momenta.transpose())#transposing the position tuple so the p1 and p2 tupple are now row vectors instead of column vectors
print(mom[0][0], type(mom))

def find_potential_energy(m, r):

  G=6.67*10**-11
  A= -1*G*m[0]*m[1]#defining the neumorator
  B = abs(r[0]-r[1])#defining the denominator as the absolute value of the difference between the vectors 
  C = np.linalg.norm(B)#normalising the difference between the vectors 
  V = A/C #formula for the potential energy 
  return V

V = find_potential_energy(mass, pos)# using the masses and the transposed position tuples 
print(f"the potential energy is :V = {V} J", type(V))#using an f string to print the value of V and to check the type of V is a float

def find_kinetic_energy(m, p):
  p1 = round(np.linalg.norm(p[0]), 5)# using the round function to return the float inside(normalising vector p1) to 5 decimal places 
  p2 = round(np.linalg.norm(p[1]), 5)# using the round function to return the float inside(normalising vector p2) to 5 decimal places 
  T = round((p1**2/(2*m[0]) + p2**2/(2*m[1])), 5)# formula to find the values of the kinetic energy 
  return T

T = find_kinetic_energy(mass, mom)#using the masses and the transposed momentum tuples 
print(f"the kinetice energy is:T = {T} J", type(T))#using an f string to print the value of the kinetic energy and to check the type of T = is a float

def find_angular_momentum(p, r):
  A = np.cross(r[0], p[0], axis = 0)# use the np.cross to find the cross product of a three row vectors r1 and p1
  B = np.cross(r[1], p[1], axis = 0)# use the np.cross to find the cross product of a three row vectors r2 and p2
  L = A + B #add the previous cross products together to obtain the angular momentum 
  return L 

L = find_angular_momentum(mom, pos)#using the transposed momentum and position tuples
print(f"the angular momentum is: {L} kgm^2/s^2", type(L))

E = T + V #final energgy is the sum of the potential energy and the kinetic energy 
print(f"the total energy and angular momentum are:E = {E} J and L = {L} kgm^2/s^2")#printed with an f string are the total energy and the angular momentum

(array([187,  33]), array([[229, 158],
       [146, 168],
       [309,  89]]), array([[103, 140],
       [166, 131],
       [188, 146]]))
[187  33]
[[229 158]
 [146 168]
 [309  89]]
 m1 = 187 m2 = 33
r1 = (103, 166, 188)
r2 = (140, 131, 146)
p1 = (229, 146, 309)
p2 = (158, 168, 89)
[103 166 188] <class 'tuple'>
229 <class 'tuple'>
the potential energy is :V = -6.235018800899111e-09 J <class 'numpy.float64'>
the kinetice energy is:T = 1378.40198 J <class 'numpy.float64'>
the angular momentum is: [ 10977  21833 -20154] kgm^2/s^2 <class 'numpy.ndarray'>
the total energy and angular momentum are:E = 1378.401979993765 J and L = [ 10977  21833 -20154] kgm^2/s^2
